-- Добавление всех валют из ЦБ РФ и ЕЦБ
INSERT INTO currencies (code, name, symbol, country) VALUES
('AZN','Azerbaijani Manat','AZN','Azerbaijan'),
('DZD','Algerian Dinar','DZD','Algeria'),
('AMD','Armenian Dram','AMD','Armenia'),
('BHD','Bahraini Dinar','BHD','Bahrain'),
('BYN','Belarusian Ruble','BYN','Belarus'),
('BOB','Bolivian Boliviano','BOB','Bolivia'),
('BRL','Brazilian Real','R$','Brazil'),
('HUF','Hungarian Forint','Ft','Hungary'),
('VND','Vietnamese Dong','VND','Vietnam'),
('HKD','Hong Kong Dollar','HK$','Hong Kong'),
('GEL','Georgian Lari','GEL','Georgia'),
('DKK','Danish Krone','kr','Denmark'),
('AED','UAE Dirham','AED','UAE'),
('EGP','Egyptian Pound','EGP','Egypt'),
('INR','Indian Rupee','INR','India'),
('IDR','Indonesian Rupiah','Rp','Indonesia'),
('IRR','Iranian Rial','IRR','Iran'),
('QAR','Qatari Riyal','QAR','Qatar'),
('KGS','Kyrgyzstani Som','KGS','Kyrgyzstan'),
('CUP','Cuban Peso','CUP','Cuba'),
('MDL','Moldovan Leu','MDL','Moldova'),
('MNT','Mongolian Tugrik','MNT','Mongolia'),
('NGN','Nigerian Naira','NGN','Nigeria'),
('NZD','New Zealand Dollar','NZ$','New Zealand'),
('NOK','Norwegian Krone','kr','Norway'),
('OMR','Omani Rial','OMR','Oman'),
('PLN','Polish Zloty','zl','Poland'),
('SAR','Saudi Riyal','SAR','Saudi Arabia'),
('RON','Romanian Leu','lei','Romania'),
('XDR','Special Drawing Rights','SDR','IMF'),
('SGD','Singapore Dollar','S$','Singapore'),
('TJS','Tajikistani Somoni','TJS','Tajikistan'),
('THB','Thai Baht','THB','Thailand'),
('BDT','Bangladeshi Taka','BDT','Bangladesh'),
('TRY','Turkish Lira','TRY','Turkey'),
('TMT','Turkmenistani Manat','TMT','Turkmenistan'),
('UZS','Uzbekistani Som','UZS','Uzbekistan'),
('UAH','Ukrainian Hryvnia','UAH','Ukraine'),
('CZK','Czech Koruna','Kc','Czech Republic'),
('SEK','Swedish Krona','kr','Sweden'),
('ETB','Ethiopian Birr','ETB','Ethiopia'),
('RSD','Serbian Dinar','din','Serbia'),
('ZAR','South African Rand','R','South Africa'),
('KRW','South Korean Won','KRW','South Korea'),
('MMK','Myanmar Kyat','K','Myanmar'),
('ISK','Icelandic Krona','kr','Iceland'),
('ILS','Israeli Shekel','ILS','Israel'),
('MXN','Mexican Peso','$','Mexico'),
('MYR','Malaysian Ringgit','RM','Malaysia'),
('PHP','Philippine Peso','PHP','Philippines')
ON CONFLICT (code) DO NOTHING;

SELECT COUNT(*) AS total_currencies FROM currencies;
